// Nombres de provincia exactos que usa el resto del proyecto: son los mismos
// valores de `province` en `/data/municipios.json` (la fuente que ya usa
// MunicipioAutocomplete/StepUbicacion al publicar un anuncio), que es también
// el string que queda guardado en Listing.province y el que SearchService
// filtra con match EXACTO (`province = "..."` en Meilisearch — ver
// search.service.ts). Si `/data/municipios.json` cambia sus nombres de
// provincia, esta lista debe regenerarse a la vez o el filtro dejará de
// matchear.
export const PROVINCIAS = [
  'A Coruña',
  'Albacete',
  'Alicante/Alacant',
  'Almería',
  'Araba/Álava',
  'Asturias',
  'Ávila',
  'Badajoz',
  'Barcelona',
  'Bizkaia',
  'Burgos',
  'Cáceres',
  'Cádiz',
  'Cantabria',
  'Castellón/Castelló',
  'Ceuta',
  'Ciudad Real',
  'Córdoba',
  'Cuenca',
  'Gipuzkoa',
  'Girona',
  'Granada',
  'Guadalajara',
  'Huelva',
  'Huesca',
  'Illes Balears',
  'Jaén',
  'La Rioja',
  'Las Palmas',
  'León',
  'Lleida',
  'Lugo',
  'Madrid',
  'Málaga',
  'Melilla',
  'Murcia',
  'Navarra',
  'Ourense',
  'Palencia',
  'Pontevedra',
  'Salamanca',
  'Santa Cruz de Tenerife',
  'Segovia',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Teruel',
  'Toledo',
  'Valencia/València',
  'Valladolid',
  'Zamora',
  'Zaragoza',
] as const;
